fc-db:
  host: ${FC_DB_HOST:localhost}
  user: ${FC_DB_USER:postgres}
  pass: ${FC_DB_PASS:admin}

spring:
  datasource:
    url: jdbc:postgresql://${fc-db.host}:5432/fc
    username: ${fc-db.user}
    password: ${fc-db.pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: DEBUG

